FROM php:8.2-fpm

ARG UID
ARG GID

ENV UID=${UID}
ENV GID=${GID}

# Criação de um usuario para o diretório do projeto
RUN addgroup --system --gid ${GID} jedis
RUN adduser --system --home /bin/sh --no-create-home --uid ${UID} --ingroup jedis --disabled-login --disabled-password jedis

RUN sed -i 's/user = www-data/user = jedis/g' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/group = www-data/group = jedis/g' /usr/local/etc/php-fpm.d/www.conf

# Definindo o usuario jedis como dono da pasta var/www/html
RUN chown -R ${UID}:${GID} /var/www/html

# Instalando dependencias gerais do PHP
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN apt-get update && apt-get install -y \
    git \
    libzip-dev \
    unzip \
    libpq-dev \
    libpng-dev \
    libmagickwand-dev \
    && docker-php-ext-install pdo pdo_pgsql zip \
    && docker-php-ext-install gd \
    && docker-php-ext-enable gd

# Instalando dependencias para o banco de dados
RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions @composer pdo_pgsql

# Instalando o composer para atualizar as dependencias
RUN curl -sS https://getcomposer.org/installer | /usr/local/bin/php -- --install-dir=/usr/local/bin --filename=composer

# Expondo a porta 9000 para acesso
EXPOSE 9000

# Definindo o usuario jedis para o projeto
USER jedis
