FROM nginx:1.25

ARG UID
ARG GID

ENV UID=${UID}
ENV GID=${GID}
# Criação de um usuario para o diretório do projeto
RUN addgroup --system --gid ${GID} jedis
RUN adduser --system --home /bin/sh --no-create-home --uid ${UID} --ingroup jedis --disabled-login --disabled-password jedis
RUN sed -i 's/user  nginx/user jedis/g' /etc/nginx/nginx.conf

# Copiando o projeto para a pasta var/www/html
COPY . /var/www/html

# Definindo o usuario jedis como dono da pasta var/www/html
RUN chown -R ${UID}:${GID} /var/www/html
